### ISSUE TITLE
Turn off ALL listeners?

### ISSUE THREAD

**Issue by resistdesign** [medikoo/event-emitter#13]
Is there a way to turn off all listeners, like when destroying?

**Comment by medikoo** [comment]
Yes, there's an [allOff](https://github.com/medikoo/event-emitter#alloffobj-event-emitterall-off) utility through which it can be achieved:

```javascript
var allOff = require('event-emitter/all-off');
...
allOff(emitter); // Detach all listeners for any events
...
allOff(emitter, 'change'); // Detach all listeners for 'change' event
```

**Comment by resistdesign** [comment]
Awesome!
