### ISSUE TITLE
Array prototype methods from es5-ext

### ISSUE THREAD

**Issue by maxfrigge** [medikoo/event-emitter#15]
I am having an issue where iterating with `for (key in array)` also iterates keys like e. g. `clear`. Digging deeper it appears that this could be coming from the `es5-ext` dependency of `event-emitter`. Since those are both your projects I thought it might be quicker to just ask rather then to analyse the code :)

Any chance I am on the right track here? Would there be a way to prevent this from happening?

**Comment by medikoo** [comment]
@maxfrigge I don't think it's related to this project.

Still if you're convinced about it, please prepare a reproducible case that involves smallest possible test case which relies only on `event-emitter` as its external dependency.

I'm closing as at this point I don't see it applicable here

**Comment by maxfrigge** [comment]
You are right. Found it in another dependency. Sorry for the noise.
