### ISSUE TITLE
Events don't propagate across modules?

### ISSUE THREAD

**Issue by geoidesic** [medikoo/event-emitter#17]
I'm working with a modularised nodejs application. I'm creating events in one module and subscribing to them in another module. This doesn't seem to work. Am I doing it wrong? E.g.
### module1
```
var eventEmitter = new events.EventEmitter()
module.exports = {
       addItem: function() {
            eventEmitter.emit('item_add',newItem)
       }
}
```
### module2
```
var module1 = require('module1')
var eventEmitter = new events.EventEmitter()
var listener = listener || 
eventEmitter.on('item_add',function(obj) {
    console.log('do something')
})

module1.add({some: "stuff"})
```

My event never reaches *module2*

**Comment by geoidesic** [comment]
Found a workable solution here: https://stackoverflow.com/questions/27257793/nodejs-in-memory-message-bus-using-eventemitter-for-cross-modules-communication

**Comment by medikoo** [comment]
@geoidesic from attached examples I have a notion that you didn't really use this package (at lest `new events.EventEmitter()` is not a construct it provides).

Anyway I'm glad you sorted it out
